# Generated by Django 4.0.5 on 2023-06-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/image/demo/380x320.png', upload_to='static/images/demo/'),
        ),
    ]
